### ISSUE TITLE
Generalize TracerAdvDiff module to 1D and 3D

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/PassiveTracerFlows.jl#8]
TracerAdvDiff should work seemlessly for 1D and 3D domains also.

**Comment by jbisits** [comment]
I am keen to have a look at these though not sure exactly when I will have time. Do you think it best if they are in the `TracerAdvectionDiffusion` module or should they be implemented in seperate modules e.g. `TracerAdvectionDiffusion1D`?

**Comment by navidcy** [comment]
Either way. But within the same module should work. We can use multiple dispatch based on grid type?

**Comment by jbisits** [comment]
Yep that sounds good!

**Comment by navidcy** [comment]
#55 added the 1D functionality!

**Comment by jbisits** [comment]
3D advection-diffusion to follow shortly!
